---
- name: install python packages required for ansible htpasswd module
  apt: name={{ item }} state=latest
  with_items:
  - python-passlib
  - python-bcrypt
- name: create auth config dir
  file: path=/etc/docker-registry/auth state=directory
- name: empty existing htpasswd file
  copy: content="" dest=/etc/docker-registry/auth/htpasswd
- name: set file permissions
  file: path=/etc/docker-registry/auth/htpasswd owner=root mode=0700
- name: add configured users 
  htpasswd: "path=/etc/docker-registry/auth/htpasswd state=present name={{ item.key }} password={{ item.value }} crypt_scheme=bcrypt"
  with_dict: "{{ docker_registry_users }}"
  